FROM ubuntu:latest
MAINTAINER dockerwb

# install jdk
RUN apt-get update
RUN apt-get -y install python-software-properties
RUN apt-get -y install software-properties-common
RUN add-apt-repository -y ppa:webupd8team/java
RUN apt-get update
RUN yes | apt-get -y install oracle-java8-installer
# RUN update-java-alternatives -s java-8-oracle

# install tomcat
RUN mkdir /var/tmp/tomcat
RUN wget -P /var/tmp/tomcat http://mirror.navercorp.com/apache/tomcat/tomcat-8/v8.5.30/bin/apache-tomcat-8.5.30.tar.gz
RUN tar xzf /var/tmp/tomcat/apache-tomcat-8.5.30.tar.gz -C /var/tmp/tomcat
RUN rm -rf /var/tmp/tomcat/apache-tomcat-8.5.30.tar.gz

RUN rm -rf /var/tmp/tomcat/apache-tomcat-8.5.30/webapps/ROOT/
COPY build/libs/*.war /var/tmp/tomcat/apache-tomcat-8.5.30/webapps/ROOT.war

EXPOSE 8080

# start tomcat
CMD ["./var/tmp/tomcat/apache-tomcat-8.5.30/bin/catalina.sh","run"]